# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # setup recurring environment
  setupEnvironment: 
    name: "Cache NPM & Elm"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ ubuntu-latest ]
    outputs:
      nodeElmSetup: ${{ steps.checkoutProject }} ${{ steps.setupNode }} ${{ steps.cacheNpm }} ${{ steps.cacheElm }}
    steps:
      - id: checkoutProject
      - uses: actions/checkout@v2
      
      - id: setupNode
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - id: cacheNpm
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - id: cacheElm
      - name: Cache Elm
        uses: actions/cache@v3
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-${{ hashFiles('**/elm.json') }}
          restore-keys: |
            ${{ runner.os }}-elm- 
  
  # building project
  build:
    name: "Building Project"
    needs: [ setupEnvironment ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ ubuntu-latest ]

    steps:
      - run: ${{ needs.setupEnvironment.outputs.nodeElmSetup }}

      - name: Download dependencies
        run: npm ci
      
      - name: Build
        run: npm run build --if-present
